### ISSUE TITLE
How do you pipe?

### ISSUE THREAD

**Issue by greim** [denys/co-request#11]
`yield request()` returns the finished result, so it's too late to pipe to it.

Meanwhile you can't `readable.pipe(request())` because you'd be piping to a thunk.

I'm probably missing something. Is there a way to pipe a stream to a request?

**Comment by aesopwolf** [comment]
Does this handle piping a response out to something else? Kind of like this one-line that request has on it's README

```js
req.pipe(request('http://mysite.com/doodle.png')).pipe(resp)
```

**Comment by csquared** [comment]
Can you show an example of what piping a to a response would look like?  

This:  
```javascript
function pipeResponse(requestThunk, writeable){                                                 
return function(cb){                                                                                                 requestThunk(cb).pipe(writeable);
  };                                                                                                              
 };
```

did not work.
